simulation:
  AutowareUniverse:
    ros__parameters:
      /localization/kinematic_state:
        version: 20240605 # architecture_type suffix (mandatory)
        seed: 0 # If 0 is specified, a random seed value will be generated for each run.
        nav_msgs::msg::Odometry:
          pose:
            pose:
              position:
                x:
                  error:
                    additive:
                      mean: 0.0
                      standard_deviation: 0.0
                    multiplicative:
                      mean: 0.0
                      standard_deviation: 0.0
                y:
                  error:
                    additive:
                      mean: 0.0
                      standard_deviation: 0.0
                    multiplicative:
                      mean: 0.0
                      standard_deviation: 0.0
                z:
                  error:
                    additive:
                      mean: 0.0
                      standard_deviation: 0.0
                    multiplicative:
                      mean: 0.0
                      standard_deviation: 0.0
              orientation:
                r:
                  error:
                    additive:
                      mean: 0.0
                      standard_deviation: 0.0
                    multiplicative:
                      mean: 0.0
                      standard_deviation: 0.0
                p:
                  error:
                    additive:
                      mean: 0.0
                      standard_deviation: 0.0
                    multiplicative:
                      mean: 0.0
                      standard_deviation: 0.0
                y:
                  error:
                    additive:
                      mean: 0.0
                      standard_deviation: 0.0
                    multiplicative:
                      mean: 0.0
                      standard_deviation: 0.0
          twist:
            twist:
              linear:
                x:
                  error:
                    additive:
                      mean: 0.0
                      standard_deviation: 0.0
                    multiplicative:
                      mean: 0.0
                      standard_deviation: 0.0
                y:
                  error:
                    additive:
                      mean: 0.0
                      standard_deviation: 0.0
                    multiplicative:
                      mean: 0.0
                      standard_deviation: 0.0
                z:
                  error:
                    additive:
                      mean: 0.0
                      standard_deviation: 0.0
                    multiplicative:
                      mean: 0.0
                      standard_deviation: 0.0
              angular:
                x:
                  error:
                    additive:
                      mean: 0.0
                      standard_deviation: 0.0
                    multiplicative:
                      mean: 0.0
                      standard_deviation: 0.0
                y:
                  error:
                    additive:
                      mean: 0.0
                      standard_deviation: 0.0
                    multiplicative:
                      mean: 0.0
                      standard_deviation: 0.0
                z:
                  error:
                    additive:
                      mean: 0.0
                      standard_deviation: 0.0
                    multiplicative:
                      mean: 0.0
                      standard_deviation: 0.0
