AbortWhenFail: true
Scenario:
  - {path: /home/yamasa/Documents/colcon_workspace/src/scenario_simulator.auto/open_scenario_interpreter/example/lane_change.xosc, expect: success}
  # - {path : test/scenario/yaml/failure.yaml, expect: failure}
  # - {path : test/scenario/yaml/success.yaml, expect: success}
