AbortWhenFail: true
Scenario:
  - {path: test/scenario/xosc/simple.xosc, expect: success}
  # - {path : test/scenario/yaml/failure.yaml, expect: failure}
  # - {path : test/scenario/yaml/success.yaml, expect: success}
