Scenario:
  - { path: $(find-pkg-share scenario_test_runner)/test/scenario/xosc/simple.xosc }
  # - { path: /home/yamasa/Documents/colcon_workspace/src/scenario_simulator.auto/test_runner/scenario_test_runner/test/scenario/yaml/minimal.yaml }
  - { path: $(find-pkg-share scenario_test_runner)/test/scenario/yaml/failure.yaml, expect: failure }
  - { path: $(find-pkg-share scenario_test_runner)/test/scenario/yaml/success.yaml, expect: success, step_time_ms: 2 }
