/**:
  ros__parameters:
    map_dir: "/workspace/Shiojiri_Lv4"

    respawn:
      init_lane_id: 57107
      goal_lane_id: 20976

    route_names:
      - "route1"
      - "route2"

    route:
      route1:
        start_lane_id: 57107
        route_ids: [20976]
        fix_start_pose: true
        fix_goal_pose: true
        init_start_lane: true
      route2:
        route_ids: [86, 57107]
        fix_start_pose: true
        fix_goal_pose: true
        init_start_lane: false
      # route2:
      #   route_ids: [20976]
      #   fix_start_pose: false
      #   fix_goal_pose: false
      #   init_start_lane: false

    # traffic_light_names:
    #   - "traffic_light0"

    # traffic_light:
    #   traffic_light0:
    #     traffic_light_ids: [8335, 8324]
    #     opposite_phase_ids: [8313, 8302]

    npc_names:
      - "vehicle0"
      - "vehicle1"
      - "vehicle2"
      - "vehicle3"
      - "vehicle4"
      - "vehicle5"
      - "pedestrian0"
      - "pedestrian1"
      - "pedestrian2"

    npc:
      vehicle0:
        npc_type: "parked_vehicle"
        spawn_lane_id: 19694
        goal_lane_id: 19694
        min_num: 1
        max_num: 3
        direction: "center"
      vehicle1:
        npc_type: "parked_vehicle"
        spawn_lane_id: 19885
        goal_lane_id: 19885
        min_num: 1
        max_num: 1
        direction: "center"
      vehicle2:
        npc_type: "parked_vehicle"
        spawn_lane_id: 20263
        goal_lane_id: 8022
        min_num: 0
        max_num: 1
        direction: "center"
      vehicle3:
        npc_type: "parked_vehicle"
        spawn_lane_id: 20479
        goal_lane_id: 39
        min_num: 0
        max_num: 1
        direction: "center"

      vehicle4:
        npc_type: "moving_vehicle"
        spawn_lane_id: 53400
        goal_lane_id: 80
        min_num: 1
        max_num: 2
        direction: "center"
      vehicle5:
        npc_type: "moving_vehicle"
        spawn_lane_id: 20632
        goal_lane_id: 53401
        min_num: 2
        max_num: 4
        direction: "center"

      pedestrian0:
        npc_type: "pedestrian"
        spawn_lane_id: 223
        goal_lane_id: 223
        min_num: 1
        max_num: 3
        direction: "left"
        min_speed: 0.0
        max_speed: 2.0
      pedestrian1:
        npc_type: "pedestrian"
        spawn_lane_id: 20651
        goal_lane_id: 20651
        min_num: 1
        max_num: 3
        direction: "right"
        min_speed: 0.0
        max_speed: 2.0
      pedestrian2:
        npc_type: "pedestrian"
        spawn_lane_id: 213
        goal_lane_id: 213
        min_num: 1
        max_num: 3
        direction: "very_left"
        min_speed: 0.0
        max_speed: 2.0
