Scenario:
  - path: $(find-pkg-share scenario_test_runner)/scenario/catalog/failure_detailed_message/failure_single_condition_anonymous.yaml
  - path: $(find-pkg-share scenario_test_runner)/scenario/catalog/failure_detailed_message/failure_single_condition_named.yaml
  - path: $(find-pkg-share scenario_test_runner)/scenario/catalog/failure_detailed_message/failure_single_init_action.yaml
  - path: $(find-pkg-share scenario_test_runner)/scenario/catalog/failure_detailed_message/failure_two_init_actions.yaml
  - path: $(find-pkg-share scenario_test_runner)/scenario/catalog/failure_detailed_message/failure_two_conditions_single_group_named.yaml
  - path: $(find-pkg-share scenario_test_runner)/scenario/catalog/failure_detailed_message/failure_two_conditions_single_group_one_named.yaml
  - path: $(find-pkg-share scenario_test_runner)/scenario/catalog/failure_detailed_message/failure_two_conditions_different_group_trigger_named.yaml
  - path: $(find-pkg-share scenario_test_runner)/scenario/catalog/failure_detailed_message/failure_two_conditions_different_group_trigger_anonymous.yaml
  - path: $(find-pkg-share scenario_test_runner)/scenario/catalog/failure_detailed_message/failure_three_conditions_two_groups_trigger_anonymous.yaml
  - path: $(find-pkg-share scenario_test_runner)/scenario/catalog/failure_detailed_message/failure_three_conditions_two_groups_trigger_named.yaml
