name: CheckLabel
on:
  pull_request:
    branches:
      - tmp/master

jobs:
  check_label:
    name: Check Label
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Check required label
        if: (!contains(github.event.pull_request.labels.*.name, 'bump patch')) && 
            (!contains(github.event.pull_request.labels.*.name, 'bump minor')) &&
            (!contains(github.event.pull_request.labels.*.name, 'bump majar'))
        run: exit 1
