name: Release
on:
  pull_request:
    branches:
      - tmp/master

jobs:
  check_label:
    name: Check Label
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Check required label
        if: contains(github.event.pull_request.labels.*.name, 'bump')
        run: exit 0
      - name: Throw error
        run: exit 1