name: Docker

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
  pull_request:
    paths:
      - '**'
      - '!docs/**'
      - '!README.md'
      - '!.github/**'
      - '.github/workflows/Docker.yaml'
      - '!mkdocs.yml'
  push:
    branches:
      - master
  release:
    types: [published]
jobs:
  build_docker_image:
    name: Build Docker Image
    runs-on: ${{ matrix.runs_on }}
    timeout-minutes: 720
    strategy:
      matrix:
        rosdistro: [humble]
        runs_on: [ubuntu-22.04, macos-14] # macos-14 is added for arm support. See also https://x.com/github/status/1752458943245189120?s=20
    steps:
      - name: Install docker for mac runner
        if: ${{ matrix.runs_on == 'macos-14'}}
        run: |
          brew install wget
          wget https://download.docker.com/mac/static/stable/aarch64/docker-25.0.3.tgz
          tar -xvzf docker-25.0.3.tgz
          cp docker/docker /usr/local/bin/

      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build (amd64)
        if: ${{ matrix.runs_on == 'ubuntu-22.04'}}
        run: docker build -t ghcr.io/tier4/scenario_simulator_v2:${{ matrix.rosdistro }} --platform linux/amd64 . --build-arg ROS_DISTRO=${{ matrix.rosdistro }}

      - name: Build (arm64)
        if: ${{ matrix.runs_on == 'macos-14'}}
        run: docker build -t ghcr.io/tier4/scenario_simulator_v2:${{ matrix.rosdistro }} --platform linux/arm64/v8 . --build-arg ROS_DISTRO=${{ matrix.rosdistro }}
