name: Docker

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
  pull_request:
    paths:
      - '**'
      - '!docs/**'
      - '!README.md'
      - '!.github/**'
      - '.github/workflows/Docker.yaml'
      - '!mkdocs.yml'
  push:
    branches:
      - master
  release:
    types: [published]
jobs:
  build_docker_image:
    name: Build Docker Image
    runs-on: ubuntu-20.04
    timeout-minutes: 720
    strategy:
      matrix:
        rosdistro: [humble]
        platform: ["linux/amd64"]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/bake-action@v3
        with:
          files: |
            ./docker-bake.hcl
          workdir: .
          no-cache: true
          push: ${{ github.event_name != 'pull_request' }}
          targets: |
            ${{ matrix.rosdistro }}
          set: |
            *.platform=${{ matrix.platform }}
