name: Docker

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
  pull_request:
    paths:
      - "**"
      - "!docs/**"
      - "!README.md"
      - "!.github/**"
      - ".github/workflows/Docker.yaml"
      - "!mkdocs.yml"
  push:
    branches:
      - master
  release:
    types: [published]
jobs:
  build_docker_image:
    name: Build Docker Image
    runs-on: ubuntu-22.04
    timeout-minutes: 720
    strategy:
      matrix:
        rosdistro: [humble]
    steps:
      - name: Install docker for ubuntu runner
        uses: docker/setup-buildx-action@v3

      - name: Install QEMU
        uses: docker/setup-qemu-action@v3

      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (amd64)
        uses: docker/bake-action@v3
        with:
          files: |
            ./docker-bake.hcl
          workdir: .
          no-cache: true
          push: ${{ github.event_name != 'pull_request' }}
          targets: |
            ${{ matrix.rosdistro }}
