name: Documentation

on:
  schedule:
    - cron: 0 0 * * *
  push:

jobs:
    job1:
        name: Generate Documentation
        runs-on: ubuntu-18.04
        steps:
        - uses: actions/checkout@v2-beta
        - name: Set up Python
          uses: actions/setup-python@v1
          with:
            python-version: '3.6.12'
        - name: Install
          run: pip3 install mkdocs mkdocs-material pymdown-extensions mdx_unimoji fontawesome_markdown markdown python-markdown-math plantuml-markdown
        - name: Install doxygen/depends of doxybook
          run: sudo apt install -y doxygen wget
        - name: Wget package
          run: |
            wget https://github.com/matusnovak/doxybook2/releases/download/v1.2.3/doxybook2-linux-amd64-v1.2.3.zip
            mkdir -p ~/doxybook2
            cp -rf . ~/doxybook2
            cd ~/doxybook2
            unzip doxybook2-linux-amd64-v1.2.3.zip

        # generating simulation_api package documentation
        - name: Generate doxygen for simulation_api package
          run: |
            cd docs/package/simulation_api
            doxygen Doxyfile
        - name: Generate markdown for simulation_api package
          run: |
            export PATH="$PATH:~/doxybook2/bin"
            cd docs/package/simulation_api
            mkdir -p ./markdown/Classes
            doxybook2 --input ./build/ --output ./markdown -c config.json

        # generating scenario_simulator package documentation
        - name: Generate doxygen for scenario_simulator package
          run: |
            cd docs/package/scenario_simulator
            doxygen Doxyfile
        - name: Generate markdown for scenario_simulator package
          run: |
            export PATH="$PATH:~/doxybook2/bin"
            cd docs/package/scenario_simulator
            mkdir -p ./markdown/Classes
            doxybook2 --input ./build/ --output ./markdown -c config.json

        # generating openscenario_interpreter package documentation
        - name: Generate doxygen for openscenario_interpreter package
          run: |
            cd docs/package/openscenario_interpreter
            doxygen Doxyfile
        - name: Generate markdown for openscenario_interpreter package
          run: |
            export PATH="$PATH:~/doxybook2/bin"
            cd docs/package/openscenario_interpreter
            mkdir -p ./markdown/Classes
            doxybook2 --input ./build/ --output ./markdown -c config.json

        # generating openscenario_visualization package documentation
        - name: Generate doxygen for openscenario_visualization package
          run: |
            cd docs/package/openscenario_visualization
            doxygen Doxyfile
        - name: Generate markdown for openscenario_visualization package
          run: |
            export PATH="$PATH:~/doxybook2/bin"
            cd docs/package/openscenario_visualization
            mkdir -p ./markdown/Classes
            doxybook2 --input ./build/ --output ./markdown -c config.json

        - name: Generate documentation
          run: mkdocs build
        - name: 'Upload Artifact'
          uses: actions/upload-artifact@v2
          with:
            name: site
            path: site
            retention-days: 1
        - name: Slack Notification
          uses: 8398a7/action-slack@v2
          if: failure()
          with:
            status: ${{ job.status }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
