name: Documentation

on:
  schedule:
    - cron: 0 0 * * *
  push:

jobs:
    job1:
        name: Generate Documentation
        runs-on: ubuntu-18.04
        steps:
        - uses: actions/checkout@v2-beta
        - name: Set up Python
          uses: actions/setup-python@v1
          with:
            python-version: '3.6.12'
        - name: Install 
          run: pip3 install mkdocs mkdocs-material pymdown-extensions mdx_unimoji fontawesome_markdown markdown python-markdown-math plantuml-markdown
        - name: Install doxygen/depends of doxybook
          run: sudo apt install -y doxygen argagg-dev git cmake gcc g++
        - name: Build inja
          run: | 
            git clone https://github.com/pantor/inja.git
            cd inja
            cmake .
            make -j2
            sudo make install
        - name : Build fmt
          run: | 
            git clone https://github.com/fmtlib/fmt.git
            cd fmt
            cmake .
            make -j2
            sudo make install
        - name : Build json
          run: | 
            git clone https://github.com/nlohmann/json.git
            cd json
            cmake .
            make -j2
            sudo make install
        - name : Build rang
          run: | 
            git clone https://github.com/agauniyal/rang.git
            cd rang
            cmake .
            make -j2
            sudo make install
        - name: Setup tmate session
          uses: mxschmitt/action-tmate@v1
        - name : Build doxybook2
          run: | 
            git clone https://github.com/matusnovak/doxybook2.git
            cd doxybook2
            cmake .
            make -j2
            sudo make install
        - name: Generate documentation
          run: mkdocs build
        - name: 'Upload Artifact'
          uses: actions/upload-artifact@v2
          with:
            name: site
            path: site
            retention-days: 1
        - name: Slack Notification
          uses: 8398a7/action-slack@v2
          if: failure()
          with:
            status: ${{ job.status }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}