name: DocumentationLinkCheck

on:
  pull_request:

jobs:
  pre-commit-optional:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run pre-commit
        uses: autowarefoundation/autoware-github-actions/pre-commit@v1
        with:
          pre-commit-config: https://raw.githubusercontent.com/autowarefoundation/autoware.universe/main/.pre-commit-config-optional.yaml
