name: Documentation

on:
  schedule:
    - cron: 0 0 * * *
  push:

jobs:
    job1:
        name: Generate Documentation
        runs-on: ubuntu-18.04
        steps:
        - uses: actions/checkout@v2-beta
        - name: Set up Python
          uses: actions/setup-python@v1
          with:
            python-version: '3.6.12'
        - name: Install 
          run: pip3 install mkdocs mkdocs-material pymdown-extensions mdx_unimoji fontawesome_markdown markdown python-markdown-math plantuml-markdown
        - name: Install doxygen/depends of doxybook
          run: sudo apt install -y doxygen argagg-dev wget
        - name: Wget package
          run: |
            wget https://github.com/matusnovak/doxybook2/releases/download/v1.2.3/doxybook2-linux-amd64-v1.2.3.zip
            unzip doxybook2-linux-amd64-v1.2.3.zip
        - name: Setup tmate session
          uses: mxschmitt/action-tmate@v1
        - name: Generate doxygen
          run: |
            export PATH="$PATH:$GITHUB_WORKSPACE/doxybook2-linux-amd64-v1.2.3/bin"
            cd docs/doxygen
            doxygen Doxyfile
            doxybook2 --input ./build/ --output ./markdown -c config.json
        - name: Generate documentation
          run: mkdocs build
        - name: 'Upload Artifact'
          uses: actions/upload-artifact@v2
          with:
            name: site
            path: site
            retention-days: 1
        - name: Slack Notification
          uses: 8398a7/action-slack@v2
          if: failure()
          with:
            status: ${{ job.status }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}