name: InterfaceUpdateNotification
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    paths:
      - openscenario/openscenario_interpreter_msgs/msg/*.msg
      - simulation/traffic_simulator_msgs/msg/*.msg

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - run: gh pr edit ${{ github.event.pull_request.number }} --add-label "interface breaking"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: gh pr comment  ${{ github.event.pull_request.number }} --edit-last --body "This PR breaks the interface to external services! Please see https://tier4.atlassian.net/wiki/spaces/S/pages/1984987364" || \
             gh pr comment  ${{ github.event.pull_request.number }} --body "This PR breaks the interface to external services! Please see https://tier4.atlassian.net/wiki/spaces/S/pages/1984987364"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

