name: NotifyFailure

on:
  workflow_run:
    workflows:
      - BuildTest
      - Docker
      - Documentation
      - ScenarioTest
    types: [ completed ]

jobs:
  comment-failure:
    runs-on: ubuntu-latest
    steps:
      - uses: quipper/comment-failure-action@v0.1.1
        with:
          api-token: ${{ secrets.GITHUB_TOKEN }}