name: PostCheckList
on:
  pull_request:
    branches:
      - master
    types: [opened, reopened]

jobs:
  post_check_list:
    name: PostCheckList
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    steps:
      - uses: zt4ff/auto-commenter@v2
        with:
          type: custom
          body: |
            # Checklist for reviewers ☑️
            All references to "You" in the following text refer to the code reviewer.
            - [ ] Is this pull request written in a way that is easy to read from a third-party perspective?
            - [ ] Is there sufficient information (background, purpose, specification, algorithm description, list of disruptive changes, and migration guide) in the description of this pull request?
            - [ ] If this pull request contains a destructive change, does this pull request contain the migration guide?
            - [ ] Labels of this pull request are valid?
            - [ ] All unit tests/integration tests are included in this pull request? If you think adding test cases is unnecessary, please describe why and cross out this line.
            - [ ] The documentation is enough? If you think adding documents for this pull request, is unnecessary, please describe why and cross out this line.
