name: Release
on:
  push:
    branches:
      - tmp/master

jobs:
  job1:
    name: Release
    runs-on: ubuntu-22.04
    timeout-minutes: 180
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name:
        run: |
          catkin_generate_changelog
          catkin_tag_changelog --bump patch
          catkin_package_version --bump patch

