name: Release
on:
  pull_request:
    branches:
      - master
    # types:
    #   - closed

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    container: ros:humble
    steps:
      - name: install bloom
        run: apt update && apt install -y python3-bloom git
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - run: ls -a
      - name: Setup git user
        run: |
          git config --global user.name  "Release Bot"
          git config --global user.email "action@github.com"
          git config --global --add safe.directory /__w/scenario_simulator_v2/scenario_simulator_v2
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      - name: update patch version
        if: contains(github.event.pull_request.labels.*.name, 'bump patch')
        run: |
          catkin_generate_changelog -y
          catkin_tag_changelog --bump patch
          catkin_package_version --bump patch
      - name: update minor version
        if: contains(github.event.pull_request.labels.*.name, 'bump minor')
        run: |
          ccatkin_generate_changelog -y
          catkin_tag_changelog --bump minor
          catkin_package_version --bump minor
      - name: update majar version
        if: contains(github.event.pull_request.labels.*.name, 'bump majar')
        run: |
          catkin_generate_changelog -y
          catkin_tag_changelog --bump majar
          catkin_package_version --bump majar
      # - name: commit changes
      #   run: |
      #     git add .
      #     git commit -m "bump version of scenario_simulator_v2."
      #     git push
      #   working-directory: scenario_simulator_v2
