name: Release
on:
  pull_request:
    branches:
      - master
  merge_group:
    types: [checks_requested]
    
jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    container: ros:humble
    steps:
      - name: install bloom
        if: ${{ github.event_name != 'pull_request' }}
        run: apt update && apt install -y python3-bloom git
      - name: checkout
        uses: actions/checkout@v2
        if: ${{ github.event_name != 'pull_request' }}
        with:
          ref: master
          fetch-depth: 0
          fetch-tags: true
      - name: Setup git user
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          git config --global user.name  "Release Bot"
          git config --global user.email "action@github.com"
          git config --global --add safe.directory /__w/scenario_simulator_v2/scenario_simulator_v2
      - uses: KyoriPowered/action-regex-match@v3
        if: ${{ github.event_name != 'pull_request' }}
        id: get_pull_request_number
        with:
          text: ${{ github.event.merge_group.head_ref }}
          regex: 'master/pr-([0-9]+)'
      - name: Merge branch
        if: ${{ github.event_name != 'pull_request' }}
        run: git pull origin ${{ github.event.merge_group.head_ref }}
      - name: Get labels of the pull request
        id: get_label
        uses: fml09/get-label@v0.1.1
        with:
          pull_number: ${{ steps.get_pull_request_number.outputs.group1 }}
          repo: scenario_simulator_v2
          owner: merge-queue-testing
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: bump patch version
        if: github.event_name != 'pull_request' && (contains(steps.get_label.output.labels, 'bump patch'))
        run: |
          catkin_generate_changelog -y
          catkin_tag_changelog --bump patch
          catkin_package_version --bump patch
      - name: bump minor version
        if: github.event_name != 'pull_request' && (contains(steps.get_label.output.labels, 'bump minor'))
        run: |
          catkin_generate_changelog -y
          catkin_tag_changelog --bump minor
          catkin_package_version --bump minor
      - name: bump major version
        if: github.event_name != 'pull_request' && (contains(steps.get_label.output.labels, 'bump major'))
        run: |
          catkin_generate_changelog -y
          catkin_tag_changelog --bump major
          catkin_package_version --bump major
      - name: print number
        run: echo ${{ steps.get_label.output.labels }}
      - uses: mxschmitt/action-tmate@v3
      - name: commit changes
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          git add .
          git commit -m "Bump version of scenario_simulator_v2 to version $(catkin_package_version)"
          git push
          git tag -a $(catkin_package_version) -m "release $(catkin_package_version)"
          git push origin $(catkin_package_version)
        working-directory: scenario_simulator_v2
