name: Release
on:
  pull_request:
    branches:
      - tmp/master
    types:
      - closed

jobs:
  job1:
    name: Release
    runs-on: ubuntu-22.04
    timeout-minutes: 180
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: update patch version
        if: github.event.label.name == 'bump patch'
        run: |
          catkin_generate_changelog
          catkin_tag_changelog --bump patch
          catkin_package_version --bump patch
      - name: update minor version
        if: github.event.label.name == 'bump minor'
        run: |
          catkin_generate_changelog
          catkin_tag_changelog --bump minor
          catkin_package_version --bump minor
      - name: update majar version
        if: github.event.label.name == 'bump majar'
        run: |
          catkin_generate_changelog
          catkin_tag_changelog --bump majar
          catkin_package_version --bump majar
