name: Release
on:
  pull_request:
  merge_group:
    types: [checks_requested]
    
jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    container: ros:humble
    steps:
      - name: install bloom
        if: ${{ github.event_name != 'pull_request' }}
        run: apt update && apt install -y python3-bloom git

      - name: checkout
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0
          fetch-tags: true

      - name: Setup git user
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          git config --global user.name  "Release Bot"
          git config --global user.email "action@github.com"
          git config --global --add safe.directory /__w/scenario_simulator_v2/scenario_simulator_v2

      - name: debug
        run: echo '${{ toJSON(github.event.pull_request._links.self.href) }}'

      - uses: KyoriPowered/action-regex-match@v3
        id: key
        with:
          text: ${{ github.event.pull_request._links.self.href }}
          regex: 'pulls/([0-9]+)'

      - name: debug
        run: echo label-pr-${{ steps.key.outputs.group1 }}

      - uses: KyoriPowered/action-regex-match@v3
        if: ${{ github.event_name != 'pull_request' }}
        id: get_restore_key
        with:
          text: ${{ github.event.merge_group.head_ref }}
          regex: 'master/pr-([0-9]+)'

      - name: Restore labels from cache
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/cache@v4
        with:
          path: semantic_version_bump.txt
          key: label-pr-${{ steps.get_restore_key.outputs.group1 }}
          fail-on-cache-miss: true
      
      - name: bump version
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          catkin_generate_changelog -y
          catkin_tag_changelog --bump $(cat semantic_version_bump.txt)
          catkin_package_version --bump $(cat semantic_version_bump.txt)

      - name: commit changes
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          git add .
          git commit -m "Bump version of scenario_simulator_v2 to version $(catkin_package_version)"
          git push
          git tag -a $(catkin_package_version) -m "release $(catkin_package_version)"
          git push origin $(catkin_package_version)
        working-directory: scenario_simulator_v2
