name: SaveLabelAsCache

on:
  pull_request:
    branches:
      - master

jobs:
  save_label_as_cache:
    name: SaveLabelAsCache
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: KyoriPowered/action-regex-match@v3
        id: key
        with:
          text: ${{ github.event.pull_request._links.self.href }}
          regex: 'pulls/([0-9]+)'
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Clear cache
        run: gh cache delete label-pr-${{ steps.key.outputs.group1 }}
        env:
          GH_TOKEN: ${{ github.token }}
        continue-on-error: true
      - name: Cache label
        uses: actions/cache@v4
        with:
          path: semantic_version_bump.txt
          key: label-pr-${{ steps.key.outputs.group1 }}
          save-always: true
      - name: is_bump_patch
        if: contains(github.event.pull_request.labels.*.name, 'bump patch')
        run: |
          echo patch > semantic_version_bump.txt
      - name: is_bump_minor
        if: contains(github.event.pull_request.labels.*.name, 'bump minor')
        run: |
          echo minor > semantic_version_bump.txt
      - name: is_bump_major
        if: contains(github.event.pull_request.labels.*.name, 'bump major')
        run: |
          echo major > semantic_version_bump.txt
