name: SpellCheckAll

on:
  workflow_dispatch:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Retrieve spell check dictionary
        run: |
          curl --silent --show-error \
            --output .github/workflows/autoware.json \
            https://raw.githubusercontent.com/tier4/autoware-spell-check-dict/main/cspell/.cspell.json

      - name: Merge words array
        uses: sergeysova/jq-action@v2
        with:
          cmd: 'jq -n ''{ words: [ inputs.words ] | add }'' .github/workflows/autoware.json .github/workflows/custom_spell.json > .github/workflows/words.json'

      - name: Merge config
        uses: sergeysova/jq-action@v2
        with:
          cmd: 'jq -s ''add'' .github/workflows/autoware.json .github/workflows/words.json > .github/workflows/.cspell.json'

      - name: Check spelling
        run: |
          # The cspell-action might not be able to exclude specific files.
          # So use cspell package directly instead.
          # How to exclude specific files:
          #   Ex. "**/!(*.osm|*.svg|CHANGELOG.rst)"
          npm install cspell
          ./node_modules/.bin/cspell \
            --config .github/workflows/.cspell.json \
            "**/!(CHANGELOG.rst)" \
            2> /dev/null || true
