name: SpellCheck

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

env:
  cspell-json-url: https://raw.githubusercontent.com/tier4/autoware-spell-check-dict/main/.cspell.json
  local-cspell-json: .github/workflows/custom_spell.json
  dict-packages: |
    https://github.com/tier4/cspell-dicts

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dict packages
        run: |
          for package in $(IFS=" " echo "${{ dict-packages }}"); do
            echo "Install $package."
            npm install $package
          done
        shell: bash

      - name: Retrieve remote dictionary
        run: |
          curl -fsSL -o remote.cspell.json ${{ cspell-json-url }} \
            -H "Authorization: token ${{ github.token }}"
        shell: bash

      - name: Prepare local dictionary
        run: |
          if [ -f "${{ local-cspell-json }}" ]; then
            cp ${{ local-cspell-json }} local.cspell.json || true
          else
            echo "No local dictionary found."
            echo "{}" > local.cspell.json
          fi
        shell: bash

      - name: Create combined dictionary
        run: |
          echo '{ "import": ["./remote.cspell.json", "./local.cspell.json"] }' > .cspell.json
        shell: bash

      - name: Run spell check
        uses: streetsidesoftware/cspell-action@v2
        with:
          config: .cspell.json
          incremental_files_only: true
          verbose: true
