name: Textlint

on:
  workflow_dispatch:
  push:

jobs:
    job1:
        name: Generate Documentation
        runs-on: ubuntu-20.04
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '10'
        - name: install textlint
          run: npm install --g textlint
        - name: install rule-ginger
          run: npm install --g textlint-rule-ginger